### ISSUE TITLE
Exit successfully when no types to generate

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/skill#115]
Currently we need to have different compile scripts depending whether we have graphql in the skill or not because the type generation fails if there are no types to generate, i.e., there are no graphql files in the repo. It would be good to not have to manage different package scripts across all the skills. This could be accomplished by failing gracefully when there are no types to generate.

**Comment by cdupuis** [comment]
Good point. That shouldn't be hard to do. I'll take a look.
