### ISSUE TITLE
Create edit/commit/push functionality for git

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/skill#151]
In thinking about https://github.com/atomist-skills/keep-a-changelog-skill/issues/67 , I wonder if it might be helpful to offer a function that applies a change, commits it, and pushes it. The "change" would likely be in the form of a function argument to run. The pseudo code representation would be:

1.  Execute change function
2.  Commit change
3.  Push change
4.  If push fails, `git reset --hard origin/BRANCH` GOTO 1

**Comment by cdupuis** [comment]
I like that idea.

If I understand it, I think I implemented something similar or at least the start of this: See https://github.com/atomist-skills/skill/blob/main/lib/github/pull_request.ts#L48

**Comment by cdupuis** [comment]
@ddgenome, do you want to take this?

**Comment by ddgenome** [comment]
Yes to everything.

The `persistChanges` function seems like a great start and the place to add in this idea of "retry".

I'll get started on implementing it.

Thanks for the pointers.
