### ISSUE TITLE
Possibly change @google-cloud/functions-framework dependency

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/skill#153]
Currently @google-cloud/functions appears to be an unused dev dependency. Should we consider:

-   Making it a peer dependency?
-   Making it a dependency so skills do not have to declare it?
-   Simply removing it as a dependency?

**Comment by cdupuis** [comment]
Thinking about this, I'd recommend we remove it until we know why we would need it.

**Comment by ddgenome** [comment]
So should it be a peer dependency?

**Comment by cdupuis** [comment]
I don't think so. The skills don't need it either any more. We have better ways of testing handlers now IHMO.

**Comment by ddgenome** [comment]
Oh, I thought it was used when the skill was actually run in GCF.

**Comment by cdupuis** [comment]
No, it is only there for testing the skill or rather GCF function locally.

**Comment by cdupuis** [comment]
This is now removed.
