### ISSUE TITLE
prompt command doesn't provide default values to Ms Teams 

### ISSUE THREAD

**Issue by timothysparg** [atomist-skills/skill#369]
when executing `await ctx.parameters.prompt` you are able to provide BaseParameters to your requested parameters as in the below snippet

``` javascript
	owner: {
		required: false,
		description: "The owner or something",
		defaultValue: "Barry",
	},
```

The expectation would be that this would be shown to the user when the command is displayed, but this doesn't seem to occur

![atomist-default-values](https://user-images.githubusercontent.com/6872586/118809013-626a0b00-b8aa-11eb-89f8-2e9263504d98.png)

**Comment by dansmithy** [comment]
This is fixed now.
