### ISSUE TITLE
prompt command doesn't respect length parameters in MS Teams

### ISSUE THREAD

**Issue by timothysparg** [atomist-skills/skill#370]
When executing `await ctx.parameters.prompt` you are able to provide `minLength` and `maxLength` attributes for your parameters.

The expectation would be that these commands would show a validation error if the input does not meet this criteria, but this is not the case.

![image](https://user-images.githubusercontent.com/6872586/118811473-592e6d80-b8ad-11eb-9b2b-50fa75845c15.png)

response to above input

![image](https://user-images.githubusercontent.com/6872586/118811813-b9bdaa80-b8ad-11eb-9101-7e455480566a.png)

**Comment by cdupuis** [comment]
@dansmithy could you please take a look at this?

**Comment by dansmithy** [comment]
This is fixed now.
