### ISSUE TITLE
Remove support for single dispatch

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/skill#77]
* Remove array from `ctx.configuration`
* Remove `DispatchStyle` from skill definition support

The following changes need to be made in a skill:

* In `EventHandler` instances, replace the array index to `ctx.configuration?.[0]` as `ctx.configuration` is not an array any longer. Instead use eg. `ctx.configuration.parameters`. _Warning_ the TypeScript compiler does not capture and report that API change
* Remove `dispatchStyle` from your `skill.ts` if it is being used

**Comment by ddgenome** [comment]
Won't this break pretty much every skill?

**Comment by cdupuis** [comment]
Yes, hence the breaking label.

**Comment by cdupuis** [comment]
Although I actually ended up preserving the contract on `ctx.configuration` because single dispatch is not yet entirely gone (we keep it for command handlers).

**Comment by ddgenome** [comment]
So basically we should always iterate through configurations now?

**Comment by cdupuis** [comment]
No, the opposite. Event handlers will only ever have one configuration. Commands potentially multiple.

**Comment by ddgenome** [comment]
Oh right, that always confused me.

> Although I actually ended up preserving the contract on `ctx.configuration`

Does that mean it is still an array? Does it mean it will remain an array?

**Comment by cdupuis** [comment]
Yes, I left it as array until we completely remove support for multiple configurations. 

I do wonder however if we should remove the array from events as that doesn't make any sense any longer. But this would be a pretty breaking change which I think would be caught be the compiler? WDYT @ddgenome

**Comment by ddgenome** [comment]
I think the less complex the better, but having a single-element array is not the end of the world. That has always been the case with the data element on the subscription anyway. I suppose there is no way to get rid of that.

Since it is early days, compilation will catch it, it simplifies things, and we are removing support for multiple configurations/single dispatch, it seems to make sense to remove it.
